repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
    args:
    - --allow-multiple-documents
  - id: detect-private-key
  - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.2
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
    args:
    - --hook-config=--path-to-file=README.md
    - --hook-config=--create-file-if-not-exist=true
    - --args=--lockfile=false
  - id: terraform_tflint
    args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
  - id: terraform_tfsec
    args:
    - --args=--no-color --concise-output

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint

# - repo: https://github.com/tanrobotix/mdlink-check-precommit.git
#   rev: v1.0.2
#   hooks:
#   - id: markdown-link-check

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.20
  hooks:
  - id: shellcheck

- repo: https://github.com/adrienverge/yamllint
  rev: v1.30.0
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --implicit_start]
    exclude: kustomization.yaml

- repo: https://github.com/crate-ci/typos
  rev: v1.14.8
  hooks:
  - id: typos
    args: []
    exclude: kustomization.yaml
